apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: parameter-store
spec:
  provider: aws
  parameters:
      objects: |
          - objectName: "/dbpasswd"
            objectType: "ssmparameter"
