apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 2Gi   # Adjust the storage size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: efs-storage-class
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e24f4f47c845a752 
