apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-new
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-storage-class
  resources:
    requests:
      storage: 2Gi   # Requested storage size, should match the PV size
